# $FreeBSD$

PORTNAME=	libCello
PORTVERSION=	1.1.7
CATEGORIES=	devel
MASTER_SITES=	http://libcello.org/static/

MAINTAINER=	matthew.closson@gmail.com
COMMENT=	Higher level programming in C

LICENSE=	BSD2CLAUSE

USES=		gmake

.include <bsd.port.mk>
